version: 2

jobs:
  build:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote
      - run: make

workflows:
  version: 2
  build:
    jobs:
      - build
